import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import {serviceDb,publicDb} from '../../lib/server/supabase';
test('find a room, route across floors, accessible failure, English and QR deep link',async({page})=>{
 await page.goto('/');await page.getByRole('textbox',{name:'Zoek lokaal of voorziening'}).fill('f 3 025');await page.getByRole('button',{name:/F3.025.*R10/}).click();await expect(page.getByRole('heading',{name:'F3.025'})).toBeVisible();await page.getByRole('button',{name:'Route hierheen'}).click();await page.getByRole('textbox',{name:'Zoek huidige locatie'}).fill('ishop');await page.getByRole('button',{name:/iShop.*R8.*0\.26/i}).click();await page.getByRole('button',{name:'Toon route'}).click();await expect(page.getByText(/Kaartindicatie/)).toBeVisible();await page.getByRole('button',{name:'Volgende routefase'}).click();await page.getByRole('switch',{name:'Toegankelijke route'}).click();await page.getByRole('button',{name:'Toon route'}).click();await expect(page.getByText(/Geen geverifieerde toegankelijke route/)).toBeVisible();await page.getByRole('button',{name:'Switch to English'}).click();await expect(page.getByRole('heading',{name:'Where are you heading?'})).toBeVisible();await page.goto('/map?from=qr:R10_MAIN_ENTRANCE&to=F3025');await expect(page.getByRole('heading',{name:'To F3.025'})).toBeVisible();
});
test('searches the same locations for From and To and keeps swap URL state',async({page})=>{await page.goto('/map?to=F3025&navigate=1');await page.getByRole('textbox',{name:'Zoek huidige locatie'}).fill('ishop');await page.getByRole('button',{name:/iShop.*R8.*0\.26/i}).click();await page.getByRole('button',{name:'Wissel start en bestemming'}).click();await expect(page.getByRole('heading',{name:'Naar 0.26'})).toBeVisible();await expect(page).toHaveURL(/from=F3025/);await expect(page).toHaveURL(/to=ishop/);});
test('mobile map and search fit 320px, keyboard access and accessibility audit',async({page})=>{await page.setViewportSize({width:320,height:740});await page.goto('/');await expect(page.getByRole('heading',{name:'Waar moet je heen?'})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.getByRole('textbox',{name:'Zoek lokaal of voorziening'}).fill('library');await page.keyboard.press('ArrowDown');await page.keyboard.press('Enter');await expect(page.getByRole('heading',{name:'Bibliotheek',level:2})).toBeVisible();const results=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();expect(results.violations).toEqual([]);await page.screenshot({path:'outputs/mobile.png',fullPage:true});});
test('public cannot enter admin data or mutate protected resources',async({request,page})=>{await page.goto('/admin');await expect(page.getByLabel('Wachtwoord / Password')).toBeVisible();for(const table of ['locations','route_nodes','hidden_gems']){expect((await request.get('/api/admin/'+table)).status()).toBe(401);expect((await request.post('/api/admin/'+table,{data:{id:'anything',status:'approved'}})).status()).toBe(401);}const db=publicDb();const change=await db.from('locations').update({status:'archived'}).eq('id','library').select();expect(change.error!==null||change.data?.length===0).toBe(true);const privilege=await db.from('admin_profiles').insert({user_id:process.env.TEST_ADMIN_ID});expect(privilege.error).not.toBeNull();const signup=await db.auth.signUp({email:'blocked-'+Date.now()+'@example.com',password:'Rejected-Only-Password123!'});expect(signup.error).not.toBeNull();});
test('real Supabase submission, photo moderation, publishing and deduplicated likes',async({page,browser})=>{
 test.skip(!process.env.TEST_ADMIN_EMAIL,'Requires provisioned admin');const title='QA temporary gem '+Date.now();let gemId:string|undefined;
 try{await page.goto('/gems');await page.getByRole('button',{name:'Deel een Hidden Gem'}).click();await page.getByLabel('Titel',{exact:true}).fill(title);await page.getByLabel('Beschrijving').fill('Temporary integration test for moderated campus submissions.');await page.getByRole('combobox',{name:'Locatie',exact:true}).click();await page.getByRole('option',{name:'Bibliotheek',exact:true}).click();await page.getByLabel('Foto (optioneel, max. 3 MB)').setInputFiles('public/icon-192.png');await page.waitForTimeout(3200);await page.getByRole('button',{name:'Verstuur mijn ontdekking'}).click();await expect(page.getByRole('status')).toContainText('Je tip wordt eerst even gecontroleerd');
 const {data,error}=await serviceDb().from('hidden_gems').select('*').eq('title',title).single();expect(error).toBeNull();gemId=data!.id;expect(data!.status).toBe('pending');expect(data!.photo_path).toBeTruthy();expect((await publicDb().from('hidden_gems').select('id').eq('id',gemId!)).data).toEqual([]);expect((await page.request.get('/api/gems/'+gemId+'/photo')).status()).toBe(404);
 const admin=await browser.newPage();await admin.goto('/admin/gems');await admin.getByLabel('E-mail',{exact:true}).fill(process.env.TEST_ADMIN_EMAIL!);await admin.getByLabel('Wachtwoord / Password').fill(process.env.TEST_ADMIN_PASSWORD!);await admin.getByRole('button',{name:'Inloggen / Sign in'}).click();const card=admin.locator('article').filter({hasText:title});await expect(card).toBeVisible();await card.getByRole('button',{name:'Goedkeuren / Approve'}).click();await expect(card.getByText('approved',{exact:true})).toBeVisible();await page.reload();const publicCard=page.locator('article').filter({hasText:title});await expect(publicCard).toBeVisible();await publicCard.getByRole('button',{name:'Like '+title}).click();await expect(publicCard.getByRole('button',{name:'Like '+title})).toContainText('1');const repeat=await page.request.post('/api/gems/'+gemId+'/like');expect(repeat.status()).toBe(200);expect((await repeat.json()).likes).toBe(1);expect((await page.request.get('/api/gems/'+gemId+'/photo')).status()).toBe(200);await admin.close();
 }finally{if(gemId){const db=serviceDb();const {data}=await db.from('hidden_gems').select('photo_path').eq('id',gemId).maybeSingle();await db.from('hidden_gems').delete().eq('id',gemId);if(data?.photo_path)await db.storage.from('gem-photos').remove([data.photo_path]);}}
});
test('admin can edit data, produce QR and inspect maps; landing screenshot',async({page})=>{test.skip(!process.env.TEST_ADMIN_EMAIL,'Requires provisioned admin');await page.goto('/admin/maps');await page.getByLabel('E-mail',{exact:true}).fill(process.env.TEST_ADMIN_EMAIL!);await page.getByLabel('Wachtwoord / Password').fill(process.env.TEST_ADMIN_PASSWORD!);await page.getByRole('button',{name:'Inloggen / Sign in'}).click();await expect(page.getByRole('heading',{name:'Kaarteditor / Map editor'})).toBeVisible();await page.goto('/admin/qr');await page.getByRole('button',{name:'QR export'}).first().click();await expect(page.getByRole('link',{name:'Download PNG'})).toBeVisible();await page.goto('/');await page.screenshot({path:'outputs/desktop.png',fullPage:true});});
