'use client';
import {useMemo,useState,useEffect} from 'react';
import {ChevronLeft,ChevronRight,X,Accessibility,Navigation} from 'lucide-react';
import {Switch} from '@/components/ui/switch';
import type {CampusData,Locale,Location} from '@/lib/campus/types';
import {shortestPath,routeStages,type Route} from '@/lib/routing/graph';
import {Picker} from './picker';
import {Feedback} from './community';
import {track} from '@/lib/campus/analytics';
const param=(key:string)=>typeof window==='undefined'?null:new URLSearchParams(window.location.search).get(key);
export function RoutePanel({data,to,locale,from,setFrom,onRoute,onStop,onFloor,onPick}:{data:CampusData;to:Location;locale:Locale;from:string;setFrom:(id:string)=>void;onRoute:(r:Route|null)=>void;onStop:()=>void;onFloor:(id:string)=>void;onPick:()=>void}){
 const en=locale==='en',[accessible,setAccessible]=useState(()=>param('accessible')==='1'),[attempted,setAttempted]=useState(()=>!!from&&!!param('from')&&!!param('to')),[stage,setStage]=useState(()=>Math.max(0,Number(param('stage'))||0)),[finished,setFinished]=useState(false);
 const active=useMemo(()=>attempted&&to.node_id?shortestPath(data.nodes,data.edges,from,to.node_id,accessible):null,[attempted,data,from,to.node_id,accessible]);
 const stages=useMemo(()=>active?routeStages(active):[],[active]),current=Math.min(stage,Math.max(0,stages.length-1));
 useEffect(()=>{onRoute(active);if(active&&stages[current])onFloor(stages[current].floor_id);},[active,current,stages,onRoute,onFloor]);
 const options=useMemo(()=>data.locations.filter(l=>l.node_id).map(l=>({value:l.node_id!,label:l.name[locale]+' · '+l.building_id})).filter((l,i,all)=>all.findIndex(x=>x.value===l.value)===i),[data,locale]);
 function updateUrl(nextStage=0,start=true){const url=new URL(window.location.href);const raw=url.searchParams.get('from');const qr=raw?.startsWith('qr:')?data.qr.find(q=>q.code===raw.slice(3)):null;url.searchParams.set('from',qr?.route_node_id===from?raw!:from);url.searchParams.set('to',to.id);url.searchParams.set('accessible',accessible?'1':'0');url.searchParams.set('stage',String(nextStage));if(start)url.searchParams.set('route','active');window.history.replaceState(null,'',url);}
 function start(){setAttempted(true);setStage(0);setFinished(false);updateUrl();track(accessible?'accessible_route_start':'route_start',{location_id:to.id});}
 function choose(id:string){setFrom(id);setAttempted(false);setFinished(false);setStage(0);}
 const stageFloor=data.floors.find(f=>f.id===stages[current]?.floor_id),nextFloor=data.floors.find(f=>f.id===stages[current+1]?.floor_id);
 const nextEdge=active?.edges.find((_,i)=>active.nodes[i].id===stages[current]?.nodes.at(-1)?.id);
 const floorLabel=(level:number)=>level===0?(en?'Ground floor':'Begane grond'):(en?'Floor ':'Verdieping ')+level;
 return <section className="panel route-panel" aria-label={en?'Your route':'Jouw route'}><div className="sheet-handle" aria-hidden="true"/><div className="panel-heading"><span className="badge">{en?'Your route':'Jouw route'}</span><button className="icon-button" aria-label={en?'Close route':'Route sluiten'} onClick={onStop}><X size={20}/></button></div><h2>{en?'To ':'Naar '}{to.room_code||to.name[locale]}</h2><p className="location-meta">{to.building_id} · {floorLabel(data.floors.find(f=>f.id===to.floor_id)?.level??0)}</p>
 {!active&&!finished&&<><h3>{en?'Where are you now?':'Waar ben je nu?'}</h3><div className="entrance-choices">{['R8','R10'].map(b=>{const loc=data.locations.find(l=>l.id===b+'_MAIN');return loc?.node_id&&<button key={b} className="secondary-button" aria-pressed={from===loc.node_id} onClick={()=>choose(loc.node_id!)}>{en?b+' main entrance':'Hoofdingang '+b}</button>;})}</div><Picker label={en?'Search current location':'Zoek huidige locatie'} value={from} onChange={choose} options={options}/><button className="text-link" onClick={onPick}>{en?'Choose starting point on map':'Kies startpunt op kaart'} →</button><small className="form-note">{en?'Scan a CampusKompas QR code on campus to use that starting point.':'Scan een CampusKompas-QR op de campus om dat startpunt te gebruiken.'}</small></>}
 {!finished&&<label className="toggle-line accessible-control"><Switch aria-label={en?'Accessible route':'Toegankelijke route'} checked={accessible} onCheckedChange={v=>{setAccessible(v);setAttempted(false);onRoute(null);const url=new URL(window.location.href);url.searchParams.set('accessible',v?'1':'0');url.searchParams.delete('route');window.history.replaceState(null,'',url);}}/><Accessibility size={20}/><span>{en?'Accessible route':'Toegankelijke route'}<small>{en?'Only verified step-free connections':'Alleen gecontroleerde drempelvrije verbindingen'}</small></span></label>}
 {!active&&!finished&&<button className="primary-button" disabled={!from} onClick={start}><Navigation size={18}/>{en?'Show route':'Toon route'}</button>}
 {attempted&&!active&&!finished&&<p className="route-unavailable" role="status">{accessible?(en?'No verified accessible route is available. Ask reception for assistance.':'Geen geverifieerde toegankelijke route beschikbaar. Vraag de receptie om hulp.'):(en?'A complete route is not available yet. Your destination is marked on the correct floor. Ask reception for the remaining directions.':'Een volledige route is nog niet beschikbaar. Je bestemming staat op de juiste verdieping aangegeven. Vraag de receptie om de verdere looproute.')}</p>}
 {active&&!finished&&<>{!active.verified&&<p className="route-beta">{en?'Plan-based preview · campus check still needed':'Kaartindicatie · controle op campus nog nodig'}</p>}<div className="next-step"><span className="eyebrow">{en?'CURRENT STAGE':'HUIDIGE ROUTEFASE'}</span><h3>{stageFloor?.building_id} · {floorLabel(stageFloor?.level??0)}</h3><p>{current===stages.length-1?(en?'Follow the highlighted corridor towards your destination. Find the room label on the map.':'Volg de gemarkeerde gang richting je bestemming. Zoek het lokaalnummer op de kaart.'):(en?'Follow the highlighted part of the route.':'Volg het gemarkeerde deel van de route.')}</p>{nextFloor&&<strong>{nextFloor.building_id!==stageFloor?.building_id?(en?'Next: leave '+stageFloor?.building_id+' and go to the '+nextFloor.building_id+' entrance.':'Hierna: verlaat '+stageFloor?.building_id+' en ga naar de ingang van '+nextFloor.building_id+'.'):(nextEdge?.edge_type==='elevator'?(en?'Lift':'Lift'):(en?'Stairs':'Trap'))+' → '+floorLabel(nextFloor.level)}</strong>}</div><div className="stage-control"><button aria-label={en?'Previous route stage':'Vorige routefase'} disabled={current===0} onClick={()=>{setStage(current-1);updateUrl(current-1);}}><ChevronLeft size={18}/></button><span>{en?'Stage ':'Fase '}{current+1} {en?'of':'van'} {stages.length}</span><button aria-label={en?'Next route stage':'Volgende routefase'} disabled={current===stages.length-1} onClick={()=>{setStage(current+1);updateUrl(current+1);}}><ChevronRight size={18}/></button></div><progress value={current+1} max={stages.length} aria-label={en?'Route progress':'Routevoortgang'}/><details className="route-overview"><summary>{en?'All stages':'Alle routefasen'}</summary><ol>{stages.map((s,i)=>{const f=data.floors.find(f=>f.id===s.floor_id);return <li key={i}><button className="text-link" aria-current={current===i?'step':undefined} onClick={()=>{setStage(i);updateUrl(i);}}>{i+1}. {f?.building_id} · {floorLabel(f?.level??0)}</button></li>;})}</ol></details><button className="secondary-button" onClick={()=>{setFinished(true);onRoute(null);track('route_complete',{location_id:to.id});const url=new URL(window.location.href);url.searchParams.delete('route');url.searchParams.delete('from');url.searchParams.delete('stage');window.history.replaceState(null,'',url);}}>{en?'Finish route':'Route afronden'}</button><button className="text-link" onClick={()=>{setAttempted(false);onRoute(null);}}>{en?'Change starting point':'Startpunt wijzigen'}</button></>}
 {finished&&<><h3>{en?'Route finished':'Route afgerond'}</h3><Feedback locale={locale} context="route" entityId={to.id}/><button className="secondary-button" onClick={onStop}>{en?'View location':'Bekijk locatie'}</button></>}
 </section>;
}
