'use client';
import Image from 'next/image';
import {useState,useEffect} from 'react';
import {TransformWrapper,TransformComponent,useControls} from 'react-zoom-pan-pinch';
import {Plus,Minus,Maximize,Info,MapPin} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import type {CampusData,Floor,Locale,Location} from '@/lib/campus/types';
import type {Route} from '@/lib/routing/graph';
function MapControls({en,selected}:{en:boolean;selected:string|undefined}) {const {zoomIn,zoomOut,resetTransform,zoomToElement}=useControls();useEffect(()=>{if(selected)void zoomToElement('original-marker-'+selected,2.2,0);},[selected,zoomToElement]);return <div className="map-controls"><button aria-label={en?'Zoom in':'Inzoomen'} onClick={()=>zoomIn()}><Plus/></button><button aria-label={en?'Zoom out':'Uitzoomen'} onClick={()=>zoomOut()}><Minus/></button><button aria-label={en?'Reset map':'Kaart herstellen'} onClick={()=>resetTransform()}><Maximize/></button></div>;}
export function MapInformation({data,locale}:{data:CampusData;locale:Locale}){
 const [open,setOpen]=useState(false);const en=locale==='en';
 return <><button className="text-link map-info" onClick={()=>setOpen(true)}><Info size={15}/>{en?'Map information':'Kaartinformatie'} <span className="badge">Beta</span></button><Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogTitle>{en?'About this campus map':'Over deze campuskaart'}</DialogTitle><DialogDescription>{en?'Original NHL Stenden floor plans with a searchable room index.':'Originele NHL Stenden-plattegronden met een doorzoekbare lokalenlijst.'}</DialogDescription><p>{en?'Plans: NHL Stenden guide, pages 18–25, public copy hosted by ETEN (2024). The current edition is on the university intranet. Room names and usage may have changed. Markers identify printed labels, not surveyed doors.':'Plattegronden: NHL Stenden-gids, pagina 18–25, openbare kopie bij ETEN (2024). De actuele editie staat op het hogeschoolintranet. Lokaalnamen en gebruik kunnen gewijzigd zijn. Markers wijzen het gedrukte label aan, geen ingemeten deur.'}</p><p>{en?'Route previews follow traced plan corridors and still need an on-campus check. Doors, closures and step-free access have not been confirmed. Accessible mode only uses connections explicitly verified by an administrator. Missing route sections are never filled with a straight line.':'Routevoorbeelden volgen overgenomen gangen op de kaart en moeten nog op de campus worden gecontroleerd. Deuren, afsluitingen en drempelvrije toegang zijn niet bevestigd. Toegankelijke routes gebruiken alleen door een beheerder geverifieerde verbindingen. Ontbrekende routedelen worden nooit met een rechte lijn aangevuld.'}</p><div className="source-list">{data.sources.map(s=><div key={s.id}><a className="text-link" href={s.url} target="_blank" rel="noreferrer">{s.title} ↗</a><small>{en?'Checked':'Gecontroleerd'}: {s.verified_at} · {s.verification_status==='verified'?(en?'Source checked':'Bron gecontroleerd'):(en?'Needs review':'Controle nodig')}</small></div>)}</div></DialogContent></Dialog></>;
}
export function UnifiedMap({floor,locale,selected,data,onSelect,route=null,from=''}:{floor:Floor;locale:Locale;selected:Location|null;data:CampusData;onSelect:(location:Location)=>void;route?:Route|null;from?:string}) {
 const en=locale==='en',available=['R8','R10'].includes(floor.building_id)&&floor.level>=0&&floor.level<=3;
 const [rooms,setRooms]=useState(false);
 const places=data.locations.filter(l=>l.floor_id===floor.id&&l.map_x!=null&&l.map_y!=null&&(l.category_id!=='room'||rooms||selected?.id===l.id));
 const start=data.nodes.find(n=>n.id===from&&n.floor_id===floor.id);
 const paths=route?.edges.filter((e,i)=>route.nodes[i].floor_id===floor.id&&route.nodes[i+1].floor_id===floor.id&&e.map_path?.length);
 if(!available)return <p className="notice">{en?'No published floor plan available.':'Geen gepubliceerde plattegrond beschikbaar.'}</p>;
 return <section className="official-map" aria-label={en?'NHL Stenden floor plan':'Plattegrond NHL Stenden'}>
 <div className="official-map-heading"><strong>{floor.building_id} · {floor.level===0?(en?'Ground floor':'Begane grond'):(en?'Floor ':'Verdieping ')+floor.level}</strong><button className="text-link" aria-pressed={rooms} onClick={()=>setRooms(!rooms)}>{rooms?(en?'Hide room markers':'Lokaalmarkers verbergen'):(en?'Show room markers':'Lokaalmarkers tonen')}</button></div>
 <div className="map-canvas official-canvas"><TransformWrapper key={floor.id} minScale={.7} maxScale={8} initialScale={1} centerOnInit limitToBounds={false} panning={{excluded:['button']}}>
 <TransformComponent wrapperClass="map-transform" contentClass="official-map-content">
 <div className="original-page"><Image src={'/maps/'+floor.building_id.toLowerCase()+'-'+floor.level+'.webp'} width={1489} height={1489} unoptimized alt={(en?'NHL Stenden floor plan, ':'NHL Stenden-plattegrond, ')+floor.building_id+', '+(en?'floor ':'verdieping ')+floor.level} draggable={false}/>
 <svg className="original-route-overlay" viewBox="0 0 100 100" aria-label={en?'Route on this floor':'Route op deze verdieping'}>{paths?.map(e=><g key={e.id}><polyline points={e.map_path!.map(p=>p.join(',')).join(' ')} fill="none" stroke="white" strokeWidth="1.2" strokeLinejoin="round"/><polyline className="route-path" points={e.map_path!.map(p=>p.join(',')).join(' ')} fill="none" stroke="#155c48" strokeWidth=".65" strokeDasharray={e.verification_status==='verified'?undefined:'1 .5'} strokeLinejoin="round"/></g>)}</svg>
 {places.map(l=><button key={l.id} id={"original-marker-"+l.id} data-location={l.id} className={'official-hotspot '+(selected?.id===l.id?'selected':'')+' '+(l.category_id==='room'?'room-pin':'')} style={{left:l.map_x+'%',top:l.map_y+'%'}} aria-label={(en?'Select ':'Selecteer ')+l.name[locale]} aria-pressed={selected?.id===l.id} title={l.name[locale]} onClick={()=>onSelect(l)}>{selected?.id===l.id?<MapPin size={20}/>:l.category_id==='room'?'·':'i'}{selected?.id===l.id&&<span className="selected-map-label">{l.room_code||l.name[locale]}</span>}</button>)}
 {start?.map_x!=null&&start.map_y!=null&&<div className="origin-pin" style={{left:start.map_x+'%',top:start.map_y+'%'}} aria-label={en?'Starting point':'Startpunt'}><span>S</span></div>}
 </div></TransformComponent><MapControls en={en} selected={selected?.floor_id===floor.id?selected.id:undefined}/></TransformWrapper></div>
 <div className="map-caption"><span><MapPin size={14}/>{selected?.floor_id===floor.id?selected.name[locale]:(en?'Tap a place for more information':'Tik op een plek voor meer informatie')}</span><MapInformation data={data} locale={locale}/></div>
 </section>;
}
